### ISSUE TITLE
Support Windows x32 and MacOS

### ISSUE THREAD

**Issue by gravit0** [JnCrMx/discord-game-sdk4j#19]
Hey. Is it possible to add support for Windows x32 and macOS?
DiscordGame SDK provides libraries for these systems

**Comment by JnCrMx** [comment]
Windows x32 should be possible really easily, as I probably just need to compile the native library for a different architecture.

Sadly I have no experience with macOS development, and I'm not sure if there is a cross-compiler/toolchain that I can integrate into the existing CMake build setup.

If you have more experience in that field, I would welcome some advice or pull requests :)

**Comment by JnCrMx** [comment]
@gravit0
I managed to do the Mac OS version, see #31.
If you own a Mac or know someone who does, testing and feedback would be very much appreicated.
