### ISSUE TITLE
No way to set CreateFlags to NoRequireDiscord

### ISSUE THREAD

**Issue by artemiswkearney** [JnCrMx/discord-game-sdk4j#24]
The CreateFlags enum has two values in the Discord docs, but this library only provides `CreateParams.getDefaultFlags()`, and it doesn't look like Discord has documented anywhere what `long` value `NoRequireDiscord` corresponds to.

**Comment by JnCrMx** [comment]
Oh, thanks for bringing this up. I need to fix this since quite some time. I will add some constants or an enum (Which would you prefer?) for that.

For now: ``NoRequireDiscord`` corresponds to the value of ``1``.
```c
enum EDiscordCreateFlags {
    DiscordCreateFlags_Default = 0,
    DiscordCreateFlags_NoRequireDiscord = 1,
};
```

**Comment by artemiswkearney** [comment]
I'm not sure what's idiomatic in Java, but an enum sounds good?

**Comment by JnCrMx** [comment]
Please have a look at #26 and tell me what you think about it
