### ISSUE TITLE
macOS libraries

### ISSUE THREAD

**Issue by JnCrMx** [JnCrMx/discord-game-sdk4j#31]
Soooo, as requested in #19, I finally managed to make a version for Mac OS.

But I don't really have the time to test it throughly, so it would be really nice if someone, who is more familiar with Mac OS and other than me likes to use it, could test it a little (in the best case in combination with their own projects) before I make the release.

You can find the relevant artifacts in this archive:
[target.zip](https://github.com/JnCrMx/discord-game-sdk4j/files/6680840/target.zip)

As said, it would be very much appreicated if someone could test this a little and report any issues occuring.

**Comment by DeDiamondPro** [comment]
Hi, I had the time to test this now and after doing so found that it is producing an unsatisfied link error:
[crash-2021-07-21_14.37.00-client.txt](https://github.com/JnCrMx/discord-game-sdk4j/files/6855732/crash-2021-07-21_14.37.00-client.txt)

**Comment by DeDiamondPro** [comment]
nvm, your compiled build works perfectly but the snapshot one on jitpack has a build error and the file for mac just says "not found" causing errors

**Comment by JnCrMx** [comment]
> nvm, your compiled build works perfectly but the snapshot one on jitpack has a build error and the file for mac just says "not found" causing errors

Yeah, the JitPack builds are a little unfortunate. It only supports Java builds by default, so it downloads the native library builds from the GitHub release (which I need to upload before).

Hence it only works for release versions and sadly not for snapshots. If you attempt to use snapshot builds it will build the lastest Java code, but use the native libraries from the last release (and since the last release didn't include any macOS libraries, it cannot include them in the build).

**Comment by DeDiamondPro** [comment]
> > nvm, your compiled build works perfectly but the snapshot one on jitpack has a build error and the file for mac just says "not found" causing errors
> 
> Yeah, the JitPack builds are a little unfortunate. It only supports Java builds by default, so it downloads the native library builds from the GitHub release (which I need to upload before).
> 
> Hence it only works for release versions and sadly not for snapshots. If you attempt to use snapshot builds it will build the lastest Java code, but use the native libraries from the last release (and since the last release didn't include any macOS libraries, it cannot include them in the build).
> 
> P.S.: Thank you a lot for testing the library! I really appreciate your help.

No problem, thanks for making the library, my project wouldn't be possible without it!

**Comment by JnCrMx** [comment]
Closing this because of the ``0.5.4`` release. Please report errors/problems with the macOS version as new issues.

**Comment by hypherionmc** [comment]
Hey if you need a macos server to build on I would be happy to give you access to mine. I only use it for jenkins builds and tests (And no I don't want anything in return. I want to help the project cause it's awesome)
