### ISSUE TITLE
How to add buttons to an Activity?

### ISSUE THREAD

**Issue by imyoric** [JnCrMx/discord-game-sdk4j#64]
Help plz, how to add buttons to an Activity?

**Comment by skyeredwood** [comment]
Might not be possible with this library.

**Comment by JnCrMx** [comment]
Yes, unless you want just "Join" and "Spectate" buttons.

**Comment by skyeredwood** [comment]
I think it is still possible with the SDK, just hasn't been supported with the library yet. I've definitely seen custom buttons in some presences, and in some GameSDK libraries for other languages, e.g. NodeJS.

**Comment by JnCrMx** [comment]
If that is the case, they not documented in the [official Game SDK documentation](https://discord.com/developers/docs/game-sdk/activities#data-models-activity-struct).

Make sure you do not confuse the now deprecated [discord-rpc API](https://discord.com/developers/docs/rich-presence/how-to) with the [Game SDK](https://discord.com/developers/docs/game-sdk/sdk-starter-guide).

However, if there is some secret, undocumented functionality within the Game SDK allowing custom buttons, I could not be opposed to implementing them. If so, please provide some links to the libraries implementing them.

**Comment by skyeredwood** [comment]
I'm not sure where the documentation is either, but either way it is possible. You may be correct in saying that it's part of the deprecated API. Here's a library I found which supports it: https://github.com/qwertyquerty/pypresence

**Comment by JnCrMx** [comment]
Yes, according to its README the library you linked is using the deprecated RPC API.

This project only focuses on the Game SDK.
