### ISSUE TITLE
Maven Version Numbers

### ISSUE THREAD

**Issue by LakMoore** [JnCrMx/discord-game-sdk4j#68]
Would you consider making a new release but altering the version number on the Maven Repo from "v0.5.6" to "0.5.6"?

The addition of the "v" makes the version number not compliant with Maven Version numbers and my dependency manager refuses to work because of that.

https://cwiki.apache.org/confluence/display/MAVENOLD/Dependency+Mediation+and+Conflict+Resolution#DependencyMediationandConflictResolution-DependencyVersionRanges

![image](https://github.com/JnCrMx/discord-game-sdk4j/assets/6624290/7a1acde8-9b08-4ad0-9f1a-e524b85185f1)

**Comment by JnCrMx** [comment]
Hi,

In the `pom.xml` the version number is written without the "v".

The prefix is only used for the Git tags.

Furthermore, Jitpak supports leaving out the "v" and still delivers the correct artifacts.

So it should be no problem to simply use those, right?

**Comment by LakMoore** [comment]
I thought I tried it without the “v”.

I’ll give it another try.

Thanks for the reply.
