### ISSUE TITLE
onActivityJoin isn't fired

### ISSUE THREAD

**Issue by RedTeaDev** [JnCrMx/discord-game-sdk4j#89]
as title, it seem that the event `onActivityJoin` was never fired?

I have tested it on ae841453bd (master latest) and 70b1e9dda6189cd9fbdce113527a915f892bc154 (java-impl latest) and both seems never fire the event?

**Comment by JnCrMx** [comment]
Have you also tried the latest released version (which still uses the native library)?

**Comment by RedTeaDev** [comment]
if you meant tag [v0.5.5](https://jitpack.io/#JnCrMx/discord-game-sdk4j/v0.5.5), yes, it seems it didn't fire the event

However i have tested adding the event listener seems to work just fine (see: https://github.com/RedCokeDevelopment/discord-game-sdk4j/commit/52f54e480caee799a0885abdba916cba1fbee207)

**Comment by JnCrMx** [comment]
Oh, do you want to make a Pull Request for that then?

**Comment by RedTeaDev** [comment]
Sure, #90

**Comment by JnCrMx** [comment]
Thank you!
